### ISSUE TITLE
Issue colors doesn't work in Redmine 3.x

### ISSUE THREAD

**Issue by kostajh** [HolonGlobe/PurpleMine2#14]
Unless I'm missing a setting somewhere, I don't see the issue colors (shades of red, blue, white) on an issue list in Redmine 3.x.

Thanks for your work on this wonderful theme!

**Comment by mrliptontea** [comment]
I haven't got my eyes on Redmine 3 yet, so it's possible there's some breaking change, i.e. some classes were removed or modified.

I'm willing to make the theme fully compatible with versions 2.5-3, so stay tuned!

**Comment by mrliptontea** [comment]
Finally got time to set up Redmine 3 and everything seems to be working just fine.

@kostajh these colors depend on:

* priority - this changes the background, by default the lowest priority is green, default is grey, higher is blue, then light red and slightly darker red;
* issue's type - this affects the color of a link with the issue number.

Take a look at this: ![issue list screenshot](https://raw.githubusercontent.com/HolonGlobe/PurpleMine2/b2f371659a9736f0c7e9bc9059f2684840a081ae/screenshots/issues-list2.png)
The background correlates with values Wishlist/Minor/Major/Critical/Blocker and link with the type - red for bugs, purple for tasks etc.

So if it's not working you had recompiled the theme with variables `$color-priorities` and/or `$color-trackers` set to `false`.

**Comment by kostajh** [comment]
yes, you are totally right! Sorry for the incorrect report @mrliptontea

**Comment by dsgonzalezo** [comment]
Sorry but I do not know how to apply the colors to the types of issues. Currently I have 38 different types, and only 1 and I do not know how or because it has different color to the rest.
Although my query is very basic, I would appreciate your help.

Greetings.

Diego

**Comment by mrliptontea** [comment]
@dsgonzalezo I'll try to help.

First, you need to find what id each type of issue (Redmine calls them *trackers*) have.
As an admin, go to Administration → Trackers or to `/trackers` URI. There you can get each id from tracker's URL, e.g. /trackers/1/edit is id = 1. Write them down.

Next, follow the [How to customize it](https://github.com/mrliptontea/PurpleMine2#how-to-customize-it) guide in order to create and include the `_custom-variables.scss` file.

Basically, in your `_custom-variables.scss` file, you need to define colors for your custom trackers in `$tracker-custom-colors-map` variable.
For example, assuming your have trackers with ids 8, 9, and 10, like this:

```scss
$tracker-custom-colors-map: (
  8: (
    background: #ad1457,
    color:      #fff
  ),
  9: (
    background: #00695c,
    color:      #fff
  ),
  10: (
    background: #f9a825,
    color:      #fff
  ),
);
```

Lastly, run `grunt` to recompile CSS and reload the page.

Hope this helps.

**Comment by dsgonzalezo** [comment]
@mrliptontea thank you very much, it worked perfect!

I do not want to abuse your kindness, but I would like one more query regarding the themes, the project view of the last version, these are presented in column form. My problem is because I have about 10 main and up to 100 subprojects and this view complicates me, I prefer the previous one, how do I keep the previous view?

Thank you very much.

Diego

**Comment by dsgonzalezo** [comment]
@mrliptontea ah I forgot, the theme of the company logo, how do I add it? is too much and does not correspond to the original issue, sorry.

**Comment by mrliptontea** [comment]
@dsgonzalezo Re: logo - see here https://github.com/mrliptontea/PurpleMine2/issues/11#issuecomment-96417752

Re: project view - if I understand you correctly, you want to set `$use-project-tiles: false;` in your custom variables file.

😉

**Comment by dsgonzalezo** [comment]
I am impressed, not only by your work, but by your generosity and predisposition to help.
At the moment you have solved all my inconveniences.
But there is always something more, someone always comes up with one more, is there a possibility to add a link to http: // redmine / issues in the top_menu?

Thank you very much

regards

Diego

**Comment by mrliptontea** [comment]
@dsgonzalezo Thank for your kind words 😊 

As for the possibility to add links to the top menu - this would be way out of scope what theme should do. I'm sure there are plugins that allow just that.

**Comment by dsgonzalezo** [comment]
Thank you very much, you have been very useful.
Nice to meet you.
Greetings.

**Comment by dsgonzalezo** [comment]
One more question
What happens now is that, I have to update my browser with Ctrl + F5 (Deleting the cache) to be able to visualize the change in the theme. Is there any way to make it automatic? It happens that I have more than 30 users that I should ask and verify that they have performed the correct steps to display what corresponds.

Thank you very much

**Comment by mrliptontea** [comment]
@dsgonzalezo Unfortunately that's something that Redmine manages. Restarting server, however, will cause it to regenerate cache-busting timestamp, which makes sense because typically assets only change when you update themes or plugins.

So when you're happy with your changes and what to make sure all users will see them, simply run `sudo service apache2 restart` or whatever's appropriate in your case.

**Comment by dsgonzalezo** [comment]
Good afternoon, here again.
I need the color of the source of a field to vary according to the content. could do it?
Eg: if the content is "RED" the color of the room must be red, the same with green, yellow or black.

Thank you very much.
